# Nom du service (important pour que Config Server sache quel fichier charger)
spring.application.name=service-user


spring.config.import=configserver:${SPRING_CONFIG_SERVER_URL}
spring.cloud.config.enabled=true